const varieteInter = [
  '99 Luftballons (Nena)',
  'A Sky Full of Stars (Coldplay)',
  'All I Want for Christmas is You (Mariah Carey)',
  'Animals (Martin Garrix)',
  'Are you gonna go my way (Lenny Kravitz)',
  'Back in Black (AC/DC)',
  'Bad Romance (Lady Gaga)',
  'Baggy Trousers (Madness)',
  'Barbie Girl (Aqua)',
  'Basket Case (Green Day)',
  'Beggin (Madcon / Maneskin)',
  'Better off alone (Alice DJ)',
  'Billie Jean (Mickael Jackson)',
  'Black Night (Deep purple)',
  'Blinding lights (The Week End)',
  'Blurred Lines (Robin Thicke)',
  'Boogie Wonderland (Earth Wind & Fire)',
  'Breakfast in America (Supertramp) ',
  'California dreamin (Mamas and Papas / Royal Gigolos)',
  'Call Me (Blondie)',
  "Can't get you out of my head (Kylie Minogue)",
  "Can't Hold Us (Macklemore)",
  "Can't Stop (Red Hot Chili Peppers)",
  "Can't take my eyes off of you (Gloria Gaynor)",
  'Celebration (Kool & the gang)',
  'Cheerleader (OMI)',
  'Chop Suey (System of a Down)',
  'Come as You Are (Nirvana)',
  'Come out and play (The Offspring)',
  'Come togeteher (The Beatles)',
  'Cotton eye joe (Rednex)',
  'Counting Stars (One Republic) ',
  'Crazy (Gnarls Barkley, façon Soul Rebels brass Band)',
  'Crazy in Love (Beyonce)',
  'Creep (Radiohead)',
  'Daddy Cool (Boney M)',
  'Dance Monkey (Tones and I)',
  'Dancing Queen (Abba)',
  'Danza Kuduro (Lucenzo)',
  'Derecho de admision (Ska-P)',
  'Despacito (Luis Fonsi)',
  "Don't stop me now (Queen)",
  "Don't Worry (Madcon)",
  "Don't You (Simple Minds)",
  "Don't you want Me (Human League)",
  'Dragosta din tei (Ozone)',
  'El Vals Del Obrero (Ska-P)',
  'Elevation (U2)',
  'Engel (Rammstein)',
  'Enola Gay (OMD)',
  'Every breathe you take (The Police)',
  'Everybody needs somebody (The Blues Brothers)',
  'Eye of the Tiger (Survivor)',
  'Faded (Alan Walker)',
  'Feeling good (Nina Simone / Muse)',
  'Freed from desire (Gala)',
  'Freedom (Pharell Williams)',
  'Funky Town (Lipps Inc)',
  'Get Lucky (Daft Punk)',
  'Goldeneye (Tina Turner)',
  'Hallelujah (Leonard Cohen / Jeff Buckley / Bastian Baker) ',
  'Happy (Pharrell Williams)',
  'Head Bussa (Lil scrappy)',
  'Head Up (The Score)',
  'Hey Brother (Avicii) ',
  'Hey Ya (Outkast) ',
  'Highway to Hell (AC/DC)',
  'Hold the line (Toto)',
  'Houdini (Dua Lipa)',
  'Humans (The faim)',
  'I Gotta Feeling (Black Eyes Peas) ',
  'I Follow Rivers (Likke Li)',
  'I Love Rock n Roll (Joan Jett)',
  "I'm Outta Love (Anastacia)",
  "I'm so excited (Pointed Sisters)",
  'I was made for lovin you (Kiss)',
  'I Will Survive (Gloria Gaynor)',
  "It's a kind of Magic (Queen)",
  "It's my life (Bon Jovi)",
  "It's raining men (The Weather Girls / Geri Halliwell)",
  'Jerusalema (Master king G)',
  'Killing in the Name (RATM)',
  'Killing me Softly (façon Youngblood Brass Band)',
  'Knights of Cydonia (Muse)',
  'Knock on Wood (Amy Stewart)',
  'La Bamba (Richie Valens)',
  'La collegiala (Los illusionistas, pub nescafé)',
  'Last Night (Madison)',
  'Let me entertain you (Robbie Williams)',
  "Let's Get Loud (Jennifer Lopez)",
  "Let's Groove (Earth Wind & Fire)",
  'Life is life (Opus)',
  'Llovera y vo vere (La Pagetina)',
  'Lonely Day (System of a Down)',
  'Long train running (The Doobie Brothers)',
  'Mala Vida (Mano Negra)',
  'Man I Feel Like a Woman (Shania Twain)',
  'Maniac (Michael Sembello - Flashdance)',
  'Maricarmen (La Pagetina)',
  'Miranda (La Pagetina)',
  'Monday Morning (Mélanie Fiona, façon Swiss Powerbrass)',
  'Moves like jagger (Maroon five) ',
  'Mr. Saxo Beat (Alexandra Stan)',
  'My first my last my everything (Barry White)',
  'Narcotic (Liquido)',
  'No no no (Dawn Penn)',
  'Nothing Else Matters (Metallica)',
  'Numb (Linkin Park)',
  'Obladi Oblada (The Beatles)',
  'On the sly (The bamboos)',
  'Outro Lugar (Salome de Bahia)',
  'Paradise (Coldplay)',
  'Party Rock Anthem (LMFAO)',
  'Pepas (Farruko)',
  'Rivers of Babylon (Boney M)',
  'Rolling in the deep (Adele, façon Dr Brass)',
  'Romeo (Emir Kusturica) ',
  'Roxanne (The Police)',
  'Sally (Carmel)',
  'Señorita (Camilla Cabello / Shawn Mendes)',
  'Set Fire to the Rain (Adèle)',
  'Seven Nations army (The White Stripes)',
  'Shake it Off (Taylor Swift) ',
  'Should I Stay or Should I Go (The Clash)',
  'Smoke on the water (Deep Purple)',
  'Stand by Me (Ben E King)',
  'Starman (David Bowie)',
  'Staying alive (Bee Gees, façon Electro Deluxe) ',
  'Still Loving You (The Scorpions)',
  'Sunday Bloody Sunday (U2)',
  'Sugar baby love (The rubettes)',
  'Superstition (Stevie Wonder) ',
  'Surfin USA (The Beach Boys)',
  'Sweet Dreams (Marilyn Manson puis Soul Rebels Brass Band)',
  'Take me out (Franz Ferdinand)',
  'Take on Me (A-Ha / Reel Big Fish)',
  'Tainted Love (Soft Cell)',
  "The kids aren't alright (The Offspring)",
  'The Show Must go on (Queen)',
  'The Sound of Silence (Simon and Garfunkel / Pentatonix)',
  'The Trooper (Iron Maiden)',
  'This Girl (Kungs)',
  'Thriller (Mickael Jacskon)',
  'Time of my Life (Patrick Swayze / Jennifer Grey, Dirty Dancing)',
  'Todos los Dias Sale el Sol (Bongo Botrako)',
  'Toxic (Britney Spears, façon Ouiches Lorraines)',
  'Treasure (Bruno Mars) ',
  'True Sorry (Ibrahim Maalouf)',
  'Umbrella (Rihanna, façon brass band)',
  'Un Dos Tres (Ricky Martin)',
  'Una Rosa Blanca (Ibahim Maalouf)',
  'Uprising (Muse)',
  'Uptown Funk (Bruno Mars / Mark Ronson)',
  'Valerie (Amy Winehouse)',
  'Video Killed the Radio Stars (The Buggles)',
  'Viva la Vida (Coldplay)',
  'What is love (Haddaway) ',
  'You are the one that i want (Grease)',
  'You make me feel (Jimmy Sommerville)',
  'You raise me up (Secret Garden)',
  'You should be dancing (Bee Gees) ',
  'Zombie (The Cranberries)',
];

const varieteFr = [
  'A Bicyclette (Yves Montand)',
  "Céline Dion MEDLEY (J'irai où tu iras, Prière Païenne)",
  'A Nos Actes Manqués (JJ Goldman)',
  'A Nos Souvenirs (3 cafés gourmands) ',
  'Ah si tu pouvais fermer ta gueule (Patrick Sébastien)',
  'Aka Aleo (Patrick Sébastien)',
  'Alexandrie Alexandra (Claude François)',
  'Alice ça glisse (Frankie Vincent)',
  'Aline (Christophe)',
  'Allumer le feu (Johnny)',
  'Andalouse (Kendji Girac)',
  'Antisocial (Trust)',
  'Aragon et Castille (Boby Lapointe)',
  'Ballade Nord-Irlandaise (Renaud / traditionnel)',
  'Bella (Maître Gims)',
  'Bella Ciao (Maitre Gims, Vitaa, Dadju, Slimane, Naestro)',
  "C'est la vie (Khaled) ",
  "C'est quand le bonheur (Cali)",
  "C'est toi que je t'aime (Les Inconnus)",
  "Ce n'est rien (Julien Clerc)",
  'Chante (Les Forbans)',
  'Chanteur de jazz (Sardou)',
  "Chanson d'amur (As de trèfle)",
  'Chez nous (Patrick Fiori / Soprano)',
  'Cielo Ciego (Boulevard des Airs)',
  'Clown (Soprano)',
  'Color Gitano (Kendji Girac)',
  'Comment te dire Adieu (Françoise Hardy)',
  'Conquistador (Kendji Girac)',
  'Cosmo (Soprano)',
  'Couleur Café (Serge Gainsbourg)',
  'Daniela (Elmer Food Beat)',
  "Dans les yeux d'Emilie (Joe Dassin)",
  "De cap ta l'immortela (Nadau)",
  'Dégénérations (Mes Aïeux)',
  'Dis Moi Oui (Keen V)',
  'El Dulce de Leche (Tryo / LEJ)',
  'Elise et Moi (Pierre Groscolas)',
  'Emmène moi (Boulevard des airs / LEJ)',
  'Emmenez moi (Aznavour)',
  'En apesanteur (Calogero) ',
  'Et Bam (Mentissa)',
  'Etre une femme (Michel Sardou)',
  'Eve lève toi (Julie Pietri)',
  'Hier Encore (Brigitte)',
  'Il était une fois nous 2 (Joe Dassin)',
  'Il fait chaud (Patrick Sébastien) ',
  'Il jouait du piano debout (France Gall)',
  "Il suffira d'un signe (JJ Goldman)",
  "Il suffira d'un signe (JJ Goldman)",
  'Initials BB (Serge Gainsbourg)',
  "J'ai tant escamoté (Zaz)",
  'Je joue de la Musique (Calogero)',
  "Je l'aime à mourir (Francis Cabrel)",
  'Je ne regrette rien (Edith Piaf)',
  'Je ne suis pas un héros (Daniel Balavoine)',
  "Je t'emmène au vent (Louise Attaque)",
  'Je te survivrai (Jean-Pierre françois)',
  "J'veux du soleil (Au petit bonheur)",
  "L'Amerique (Joe Dassin)",
  "L'Aziza (Daniel Balavoine)",
  "L'Ecole est finie (Sheila)",
  "L'Envie (Johnny)",
  "L'Homme Pressé (Noir Désir)",
  "L'Hymne de nos campagnes (Tryo)",
  "L'instinct du meilleur (La Ruda)",
  "L'Orange (Gilbert Bécaud)",
  'La Cartouche (Sébastien Patoche)',
  'La cheu-cheu synchro',
  "La Complainte de l'Heure de Pointe (Joe Dassin)",
  'La Goffa Lolita (La Petite Culotte)',
  'La Groupie du pianiste (Michel Berger)',
  'La Grenade (Clara Luciani)',
  'La Java de Broadway (Michel Sardou)',
  'La Même (Maître Gims/Vianney)',
  'La nuit je mens (Alain Bashung)',
  "La nuit n'en finit pas (Petula Clark)",
  'La Salsa du Démon (Splendid)',
  'La Tournée du Patron (Sébastien Patoche)',
  'La Tribu de Dana (Manau)',
  'Laisse Tomber les Filles (France Gall)',
  'Laissez moi danser (Dalida)',
  "Le berger d'aure (Edmond Duplan)",
  'Le Jerk (Thierry Hazard)',
  'Le Lac (Julien Doré)',
  'Le Lion est mort ce soir (Henri Salvador, banda)',
  'Le poinçonneur des lilas (Serge Gainsbourg)',
  'Le Portrait (Calogero)',
  'Le Soldat (Florent Pagny)',
  'Le Sud (Nino Ferrer)',
  'Le Tube (Ricoune)',
  'Les acadiens (Michel Fugain)',
  'Les Bals Populaires (Michel Sardou)',
  'Les Cornichons (Nino Ferrer)',
  'Les Corons (Pierre Bachelet)',
  'Les Démons de minuit (Emile et Images)',
  'Les enfoirés (générique)',
  'Les Jolies colonies de vacances (Pierre Perret)',
  'Les lacs du conemara (Michel Sardou)',
  'Les Marionnettes (Christophe)',
  'Les oubliés (Gauvain Sers)',
  'Les plages de Nouméa (Caledo)',
  'Les Sardines (Patrick Sébastien)',
  'Li Tourner (DJ Assad)',
  'Ma Drôle de Vie (Véronique Sanson)',
  "Ma p'tite étoile (Hatik)",
  'Macumba (Jean-Pierre Mader)',
  'Magic in the air (Magic System)',
  'Magnolias for ever (Claude François)',
  'Majorettes (Bénabar)',
  'Maldon (Zouk Machine / Tropical Family)',
  'Marcia Baila (Rita Mitsouko)',
  'Marie (Johnny Hallyday)',
  "Mets de l'huile (Regg'Lyss)",
  'Mon Précieux (Soprano)',
  'Morlana (Nadau)',
  'Mundo Loco (Boulevard des airs)',
  'Né en 17 ( JJ Goldman)',
  'New York avec toi (Téléphone)',
  'Nos mains (Goldman)',
  'Nuit de Folie (Début de soirée)',
  "Oh Pétard (L'art à tatouille)",
  'On Dirait (Amir) ',
  'On écrit sur les murs (Kids united / Demis roussos)',
  "On s'est aimés comme on se quitte (Joe Dassin)",
  "On t'emmène (3 cafés gourmands)",
  "On va s'aimer (Gilbert Montagné)",
  'Papaoutai (Stromae)',
  'Partenaire Particulier ',
  'Pas de Boogie Woogie (Eddy Mitchell)',
  'Poupée de cire poupée de son (France Gall)',
  'Pour Oublier (Kendji Girac)',
  'Quand la musique est bonne (Goldman)',
  'Que Dieu me Pardonne (Kendji /Claudio Capeo)',
  'Qui Saura (Mike Brandt)',
  'Scoubidou (Sacha Distel)',
  'Siffler la haut (Joe Dassin)',
  "Soulman (Ben l'oncle soul)",
  "Sous une pluie d'étoiles (Cindy Daniel)",
  'Tahiti (Keen V)',
  "T'es ok (Ottawan)",
  'Tombé du Ciel (Jacques Higelin)',
  'Tomber la chemise (Zebda)',
  'Tourner les Serviettes (Patrick Sébastien)',
  'Tout pour ma chérie (Polnareff)',
  "Un Homme Comme Vous (Ben l'oncle Soul)",
  'Un Homme Debout (Claudio Capeo)',
  'Un métier sérieux (Keen V)',
  "Une pointe d'accent (Michel Etcheverry)",
  'Vamos a Salou (Les Gauff)',
  'Vélomoteur (Les Calamités)',
  'Vladimir (Soviet suprem)',
];

const nouveautes = [
  'Houdini (Dua Lipa)',
  "Céline Dion MEDLEY (J'irai où tu iras, Prière Païenne)",
  'La Cheu-cheu synchro',
  'Et Bam (Mentissa)',
  'Sweet Dreams (version Marilyn Manson puis Soul Rebels)',
];

const bandas = [
  "3e Mi-Temps MEDLEY (La moto, Le sport roi, Quand l'avion atterrit, Beber, La Marmite, Arrantzaleak, La pitxuri)",
  'Alma Corazon',
  'Arbola',
  'Aringoa',
  'Auteria',
  'Ba Moin en Tibo',
  'Bakalao Salao',
  'Banitos',
  'Bella Chica',
  'Caracas',
  'Didier',
  'Egun Off',
  'Eguna Jalo Arte',
  'Fanguito',
  'Fiesta Pagana',
  'Garrekin',
  'Gau Ibillera',
  'Go West',
  'Ipo y taie taie ie',
  'Jueves Gordo',
  'La chatte à la voisine',
  'La Gacela / Le Galicien',
  'La Marmite',
  'Il a fait de la moto',
  'Il est un coin de France',
  "L'encantada",
  "L'estaca",
  'La Coline',
  'La Pitxuri',
  "Le Cheikh d'Arabie",
  'Le Sport roi',
  'Le Temps des Fleurs',
  'Marioneta',
  'Maubeuge',
  'Muztafa',
  'Ole Ti To',
  'Paquito el chocolatero',
  'Pasa La Juventud',
  'Petit Gonzalez',
  'Pinocchio',
  'Piranhas',
  'Porompompero',
  'Que bonitas es la amapola',
  'Rarès Baguès',
  'Respalo',
  'Sassuna',
  'Si nos organizamos',
  'Spaghetti',
  'Tenarez',
  'The gummy bear song',
  'Tornero',
  'Vinoska',
];

const medleys = [
  'Abba (Dancing Queen, The Winner Takes it All)',
  'Annie Cordy (La bonne du curé, Tata yoyo, Chaud cacao)',
  'Ambiance (Lady lay, I Will Survive, Les Démons de Minuit, Magic in the Air, Les lacs du conémara)',
  "Balavoine (Le Chanteur, Mon Fils ma Bataille, La Vie ne m'apprend Rien, Je ne suis pas un Héros)",
  "Balavoine 2 (Sauver l'amour, l'Aziza, Je ne suis pas un héros)",
  'Calogero (La Bourgeoisie des sensations, La fin de la fin du monde, Le Portrait, Un jour au mauvais endroit)',
  "Céline Dion (J'irai où tu iras, Prière Païenne)",
  'Champions du Monde (Ramenez la coupe à la maison, Magic in the air, I Will Survive)',
  "Chantal Goya (Pandi Panda - Le Lapin - M. le Chat Botté - C'est Guignol - Bécassine)",
  'Charles Aznavour (Les Comédiens, Emmenez moi, For me formidable)',
  'Cinéma (Unchained Melody, My heart will go on, I Have Nothing, I dont want to miss a thing, Chi Mai)',
  'Claude François (Magnolias - Je vais à Rio - Cette année là - Alexandrie)  ',
  'Dance Machine (The Rythm of the Night - Sing Alleluia - No Limit - What is Love - Think About the Way)',
  'Dessins animés (Capitaine flam - Nicky Larson - Bioman - Olive et Tom)',
  "Dessins animés 2 (Les Cités d'Or - Les Mondes engloutis)",
  "Dessins animés 3 (L'île aux enfants - Croque vacances - Les Cités d'Or - Capitaine Flam)",
  'Divers : La tribu de Dana (Manau), Cosmo (Soprano), Manu Chao (Les Wampas), La Même (Vianney, Maître Gims)',
  "Earth Wind and Fire (Boogie Wonderland, Let's Groove, September)",
  'Gipsy Kings (Bamboleo - Baila Me - Volare - Djobi djoba - Pida Me La)',
  'Kendji (Gitano, Pour oublier, Conquistador)',
  'Jean-Jacques Goldman (Encore un matin, Quand la Musique est Bonne)',
  "Jean-Jacques Goldman 2 (Et on n'y peut rien, Quand la Musique est Bonne, Envole moi)",
  'Jean-Jacques Goldman 3 (Il changeait la vie, 1 2 3, La vie par procuration)',
  'Jésus, façon los arsouillos (Jésus est né en provence, Donne la paix à ton frère, Jésus reviens)',
  "Joe Dassin (Champs Elysées - Salut les amoureux - L'Amerique - Siffler la haut)",
  "Johnny (Tennessee, Noir C'est Noir, Gabrielle, Les Portes du Pénitencier, Allumer le Feu)",
  "Lama (Les Femmes de Pigale, D'aventure en aventure, L'enfant au piano, Je suis malade, Femmes femmes)",
  'Latino (La collegiala, Lambada, Bara bara)',
  'Lio (Les Brunes, Banana Split)',
  'Manu Chao (Mala Vida - Welcome to Tijuana - King of the Bongo - Pinocchio - Rumba de Barcelona)',
  'Noël (Douce Nuit - Vive le Vent - Petit Papa Noël)',
  'Rock (Jump, Thunderstruck, Highway to Hell, Smells Like teen Spirit, Antisocial, Seven nations army)',
  'Queen (We will rock you, Bohemian Rhapsody, Another one bites the dust, We are the champions)',
  'Reggae (No Woman no Cry, Reggae Night)',
  'Sardou (La Java de Broadway, Chanteur de Jazz, Les Lacs du Conemara)',
  'Sardou 2 (Femme des années 80, Afrique Adieu)',
  'Soprano (Cosmo, Mon Précieux, Dingue)',
  'Stevie Wonder (Sir Duke, Superstition, I Wish, Part Time Lover)',
  "The Beatles (Hey Jude - She's got a ticket to Ride - Let it be - Hard Days Night - Obladi Oblada)",
  'The Beatles 2 (All you need is love - Penny Lane - Help - Hey Jude)',
  'Tubes Français 2018 (Ramenez la coupe à la maison, Chez Nous, La Même, A nos Souvenirs)',
  'Village People (In The Navy - YMCA)',
];

const generiques = [
  'Game of Thrones ',
  'Ghostbusters',
  'Huit et Demi (Nino Rota)',
  'I Will follow him (Sister act)',
  'Laurel et Hardy ',
  "Le Pudding à l'Arsenic (Astérix et Cléopatre)",
  'Les bronzés font du ski ',
  "Les Mystérieuses Cités d'Or ",
  'Libéree Délivrée / Let it go (façon Brass Delirum)',
  'Mac Gyver theme (Ted Parson)',
  'Misirlou (Pulp Fiction)',
  'Rabbi Jacob ',
  'Star Wars ',
  'Téléthon (générique)',
  'The Muppet Show',
];

const divers = [
  'Barasko',
  'Besame ska',
  'Bikunbia',
  'Brooklyn (Youngblood brassband)',
  'Canon Rock (Pachelbel / Jerry C)',
  'Czardas (Monti)',
  'Dangaparence (Ska)',
  'Ecuador',
  'Fam martinik (biguine)',
  'Gimena (Latino)',
  'Grazun (Baion)',
  'In the Mood (Glenn Miller)',
  'Keep festend',
  'La Chomba (Latino)',
  'Le Danube Bleu (Joann Strauss, version Cha-cha)',
  'Le Pakistan',
  'Messe Sévillane',
  'Missié Michel (Biguine)',
  'Peas (Broken bass ensemble)',
  'Petite Fleur (Sydney Bechett)',
  'Polka n°36',
  'Mignon mignon (René la Taupe)',
  'Seo Ze (Carlinhos Brown)',
  'Saguate Cumbia',
  'Showtime (Soul Rebels brass band)',
  'Siempre vez (mambo)',
  'Solo vivir (Skalariak)',
  'Tetriskal',
  'The Movement (Youngblood Brass Band)',
  'Yadeg',
];
const tradi = [
  'Amazing Grace (Traditionnel écossais)',
  'Aurore Sand (traditionnel auvergnat)',
  'Hegoak (traditionnel basque) ',
  'Kazachoc (traditionnel russe)',
  'Santiano',
  'Se Canta (traditionnel occitan) ',
  'Balkan esma',
  'Devla (Fanfare Ciocarlia)',
  'Iag Bari (Fanfare Ciocarlia)',
  'Moliendo Café (Hugo Blanco)',
  'Vrtlog (Dejan Petrovic Big Band)',
  'Arena di Verona',
  'Ay mi sombrero',
  'Coplas',
  'Doble Mexicano',
  'Niña Pancha',
];
module.exports = {
  varieteInter,
  varieteFr,
  nouveautes,
  bandas,
  medleys,
  generiques,
  divers,
  tradi,
};
